import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>Mi App</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} h-screen`}>
        <main className="w-full h-full bg-gray-100 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}




